WebPOS/Controllers/FunctionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebPOS.Dto;
using WebPOS.Models;
using WebPOS.Option;

namespace WebPOS.Controllers
{
    [Authorize]
    public class FunctionController : Controller
    {
        private CentralDbContext db = new CentralDbContext();
        //private CentralDbContext _context = new CentralDbContext();
        //public POSTerminalController(CentralDbContext context)
        //{
        //_context = context;
        //}
        // GET: /<controller>/  
        public IActionResult Index()
        {
            ViewBag.stores = db.Function.ToList();
            return View();
        }

        public IActionResult LoadData()
        {
            try
            {
                var draw = HttpContext.Request.Form["draw"].FirstOrDefault();
                // Skiping number of Rows count  
                var start = Request.Form["start"].FirstOrDefault();
                // Paging Length 10,20  
                var length = Request.Form["length"].FirstOrDefault();
                // Sort Column Name  
                var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
                // Sort Column Direction ( asc ,desc)  
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
                // Search Value from (Search box)  
                var searchValue = Request.Form["search[value]"].FirstOrDefault();

                //Paging Size (10,20,50,100)  
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;
                int recordsTotal = 0;

                // Getting all Customer data  
                var customerData = (from tempcustomer in db.Function
                                    select tempcustomer);

                //Sorting  
                // if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDirection)))
                // {
                // customerData = customerData.OrderBy(sortColumn + " " + sortColumnDirection);
                // }
                //Search  
                if (!string.IsNullOrEmpty(searchValue))
                {
                    customerData = customerData.Where(m => m.Name == searchValue);
                }

                //total number of rows count   
                recordsTotal = customerData.Count();
                //Paging   
                var data = customerData.Skip(skip).Take(pageSize).ToList();
                //Returning Json Data  
                return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data });

            }
            catch (Exception)
            {
                throw;
            }

        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.stores = db.Function.ToList();
            ViewBag.function = db.Function.Find(id);
            var storeno = db.Function.Where(x => x.Id == id).SingleOrDefault();
            IEnumerable<SelectListItem> items = db.Function.Select(c => new SelectListItem
            {
                Value = Convert.ToString(c.Id),
                Text = c.Name,
                Selected = (c.Id == storeno.ParentId) ? true : false
            }); ;
            ViewBag.stores = items;
            return View();
        }
        [HttpPost]
        public IActionResult Edit(Function obj)
        {
            Function existing = db.Function.Find(obj.Id);
            existing.Name = obj.Name;
            existing.Url = obj.Url;
            existing.CssClass = obj.CssClass;
            existing.ParentId = obj.ParentId;
            existing.SortOrder = obj.SortOrder;
            // existing.LastDateModified = DateTime.Now;
            db.Entry(existing).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }



        [HttpPost]
        public IActionResult Delete(int id)
        {
            // string newid = @"VINGROUP\";
            //string newidnew = newid + id;
            db.Function.Remove(db.Function.Find(id));
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.stores = db.Function.ToList();
            return View();
        }
        public JsonResult CheckUsernameAvailability(int userdata)
        {
            System.Threading.Thread.Sleep(200);
            
            var SeachData = db.Function.Where(x => x.Id == userdata).SingleOrDefault();
            if (SeachData != null)
            {
                return Json(1);
            }
            else
            {
                return Json(0);
            }

        }
        [HttpPost]
        public IActionResult Add(Function obj)
        {
            

            db.Function.Add(obj);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebPOS/Views/Function/Edit.cshtml
@{
    ViewData["Title"] = "Menu hệ thống";
    ViewData["TitleActive"] = "Menu hệ thống";
    ViewData["TitleCurrent"] = "Menu hệ thống";
    
}
@model WebPOS.Dto.Function
<div class="page-header">
    <h1>
        Sửa Menu hệ thống
    </h1>
</div>
<form method="post" asp-controller="Function" asp-action="Edit" class="form-horizontal">

    <div class="form-group">
        <label class="col-sm-3 control-label no-padding-right" for="form-field-1" style="font-weight:bold;">ID </label>

        <div class="col-sm-9">
            <input type="text" id="UserName" class="col-xs-10 col-sm-5" asp-for="Id" value="@ViewBag.function.Id" readonly="readonly">
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-3 control-label no-padding-right" for="form-field-1" style="font-weight:bold;"> Tên menu </label>

        <div class="col-sm-9">
            <input type="text" id="form-field-1" class="col-xs-10 col-sm-5" required asp-for="Name" value="@ViewBag.function.Name">
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label no-padding-right" for="form-field-1" style="font-weight:bold;"> Url </label>

        <div class="col-sm-9">
            <input type="text" id="form-field-1" class="col-xs-10 col-sm-5" required asp-for="Url" value="@ViewBag.function.Url">
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label no-padding-right" for="form-field-1" style="font-weight:bold;"> Css Cass </label>

        <div class="col-sm-9">
            <input type="text" id="form-field-1" class="col-xs-10 col-sm-5"  asp-for="CssClass" value="@ViewBag.function.CssClass">
        </div>
    </div>
    <div class="form-group"> 
        <label for="form-field-select-3" class="col-sm-3 control-label no-padding-right" style="font-weight:bold;">Menu cha</label>
        <div class="col-sm-4">
            
            <select asp-for="ParentId" asp-items="@ViewBag.stores" class="chosen-select form-control col-xs-10 col-sm-5" id="form-field-select-3" data-placeholder="Chọn menu cha..." style="display: none;">
                <option value="0">Chọn menu cha</option>
            </select>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label no-padding-right" for="form-field-1" style="font-weight:bold;"> Thứ tự hiển thị </label>

        <div class="col-sm-9">
            <input type="text" id="form-field-1" class="col-xs-10 col-sm-5" required asp-for="SortOrder" value="@ViewBag.function.SortOrder">
        </div>
    </div>
    <div class="clearfix form-actions">
        <div class="col-md-offset-3 col-md-9">
            <button class="btn btn-info" type="submit">
                <i class="ace-icon fa fa-check bigger-110"></i>
                Lưu
            </button>
            <button class="btn" type="reset">
                <i class="ace-icon fa fa-undo bigger-110"></i>
                Thiết lập lại
            </button>
            <a class="btn btn-danger" href="/Function">
                <i class="ace-icon fa fa-reply align-top bigger-125"></i>Trở về danh sách
            </a>
        </div>
    </div>

</form>
@section scripts {
    <script type="text/javascript">

        jQuery(function ($) {
            $('#id-disable-check').on('click', function () {
                var inp = $('#form-input-readonly').get(0);
                if (inp.hasAttribute('disabled')) {
                    inp.setAttribute('readonly', 'true');
                    inp.removeAttribute('disabled');
                    inp.value = "This text field is readonly!";
                }
                else {
                    inp.setAttribute('disabled', 'disabled');
                    inp.removeAttribute('readonly');
                    inp.value = "This text field is disabled!";
                }
            });


            if (!ace.vars['touch']) {
                $('.chosen-select').chosen({ allow_single_deselect: true });
                //resize the chosen on window resize

                $(window)
                    .off('resize.chosen')
                    .on('resize.chosen', function () {
                        $('.chosen-select').each(function () {
                            var $this = $(this);
                            $this.next().css({ 'width': $this.parent().width() });
                        })
                    }).trigger('resize.chosen');
                //resize chosen on sidebar collapse/expand
                $(document).on('settings.ace.chosen', function (e, event_name, event_val) {
                    if (event_name != 'sidebar_collapsed') return;
                    $('.chosen-select').each(function () {
                        var $this = $(this);
                        $this.next().css({ 'width': $this.parent().width() });
                    })
                });


                $('#chosen-multiple-style .btn').on('click', function (e) {
                    var target = $(this).find('input[type=radio]');
                    var which = parseInt(target.val());
                    if (which == 2) $('#form-field-select-4').addClass('tag-input-style');
                    else $('#form-field-select-4').removeClass('tag-input-style');
                });
            }
        })
    </script>
}

WebPOS/Views/Function/Index.cshtml
@{
    ViewData["Title"] = "Menu hệ thống";
    ViewData["TitleActive"] = "Menu hệ thống";
    ViewData["TitleCurrent"] = "Menu hệ thống";


}
@model WebPOS.Dto.Function
<div class="main-content">
    <div class="main-content-inner">
        <div class="page-content">

            <!-- PAGE CONTENT BEGINS -->
            <div class="row">
                <div class="col-xs-12">
                    <div class="tabbable">
                        <ul class="nav nav-tabs" id="myTab">
                            <li class="active">
                                <a data-toggle="tab" href="#home">
                                    <i class="green ace-icon fa fa-home bigger-120"></i>
                                    Danh sách menu
                                </a>
                            </li>

                            <li>
                                <a data-toggle="tab" href="#messages">
                                    <i class="ace-icon glyphicon glyphicon-plus green bigger-110"></i>
                                    Thêm mới menu

                                </a>
                            </li>


                        </ul>

                        <div class="tab-content">
                            <div id="home" class="tab-pane fade in active">
                                <div class="clearfix">
                                    <div class="pull-right tableTools-container"></div>
                                </div>
                                <div>
                                    <table id="function-table" class="table table-striped table-bordered table-hover" width="100%" cellspacing="0">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>Tên menu</th>
                                                <th>Url</th>
                                                <th>Menu cha</th>
                                                <th>Thứ tự hiển thị</th>
                                                <th>Css class</th>
                                                <th>Chức năng</th>
                                            </tr>
                                        </thead>

                                    </table>

                                </div>
                            </div>

                            <div id="messages" class="tab-pane fade">
                                <form method="post" asp-controller="Function" asp-action="Add" class="form-horizontal">


                                    <div class="form-group">
                                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1" style="font-weight:bold;"> Id </label>

                                        <div class="col-sm-9">
                                            <input type="text" id="Id" required class="col-xs-10 col-sm-5" asp-for="Id" onchange="UserCheck()">
                                        </div>
                                    </div>
                                    <div class="row">
                                        <label class="col-sm-2"></label>
                                        <div class="col-sm-10">
                                            <p id="Status" />
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1" style="font-weight:bold;"> Tên menu </label>

                                        <div class="col-sm-9">
                                            <input type="text" id="form-field-1" required class="col-xs-10 col-sm-5" asp-for="Name">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1" style="font-weight:bold;"> Url </label>

                                        <div class="col-sm-9">
                                            <input type="text" id="form-field-1" required class="col-xs-10 col-sm-5" asp-for="Url">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="form-field-select-3" class="col-sm-3 control-label no-padding-right" style="font-weight:bold;">Menu cha</label>
                                        <div class="col-sm-4">
                                            <select asp-for="ParentId" asp-items="@(new SelectList(@ViewBag.stores,"Id", "Name"))" class="chosen-select form-control col-xs-10 col-sm-5" id="form-field-select-3" data-placeholder="Chọn cửa hàng..." style="display: none;">
                                                <option value="0">Chọn menu cha</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1" style="font-weight:bold;"> Css Class </label>

                                        <div class="col-sm-9">
                                            <input type="text" id="form-field-1" class="col-xs-10 col-sm-5" asp-for="CssClass">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1" style="font-weight:bold;"> Thứ tự hiển thị </label>

                                        <div class="col-sm-9">
                                            <input type="text" id="form-field-1" required class="col-xs-10 col-sm-5" asp-for="SortOrder">
                                        </div>
                                    </div>
                                    <div class="clearfix form-actions">
                                        <div class="col-md-offset-3 col-md-9">
                                            <button class="btn btn-info" type="submit">
                                                <i class="ace-icon fa fa-check bigger-110"></i>
                                                Lưu và tạo mới
                                            </button>
                                            <button class="btn" type="reset">
                                                <i class="ace-icon fa fa-undo bigger-110"></i>
                                                Thiết lập lại
                                            </button>
                                            
                                        </div>
                                    </div>

                                </form>
                            </div>


                        </div>
                    </div>

                </div>
            </div>

            <!-- PAGE CONTENT ENDS -->

        </div><!-- /.page-content -->
    </div>
</div><!-- /.main-content -->
<!-- inline scripts related to this page -->
@section scripts {
    <script>

         function UserCheck() {
            $("#Status").html("Kiểm tra...");
            $.post("@Url.Action("CheckUsernameAvailability", "Function")",
                {
                    userdata: $("#Id").val()
                },
            function (data) {
                if (data == 0) {
                    $("#Status").html('<font color="Green">Bạn có thể sử dụng mã này</font>');
                    $("#Id").css("border-color", "Green");

                }
                else {
                    $("#Status").html('<font color="Red">Mã này đã được sử dụng.</font>');
                    $("#Id").css("border-color", "Red");
                }
            });
        }
        $(document).ready(function ()
        {
            $('#id-disable-check').on('click', function () {
            var inp = $('#form-input-readonly').get(0);
            if (inp.hasAttribute('disabled')) {
                inp.setAttribute('readonly', 'true');
                inp.removeAttribute('disabled');
                inp.value = "This text field is readonly!";
            }
            else {
                inp.setAttribute('disabled', 'disabled');
                inp.removeAttribute('readonly');
                inp.value = "This text field is disabled!";
            }
        });


        if (!ace.vars['touch']) {
            $('.chosen-select').chosen({ allow_single_deselect: true });
            //resize the chosen on window resize

            $(window)
                .off('resize.chosen')
                .on('resize.chosen', function () {
                    $('.chosen-select').each(function () {
                        var $this = $(this);
                        $this.next().css({ 'width': $this.parent().width() });
                    })
                }).trigger('resize.chosen');
            //resize chosen on sidebar collapse/expand
            $(document).on('settings.ace.chosen', function (e, event_name, event_val) {
                if (event_name != 'sidebar_collapsed') return;
                $('.chosen-select').each(function () {
                    var $this = $(this);
                    $this.next().css({ 'width': $this.parent().width() });
                })
            });


            $('#chosen-multiple-style .btn').on('click', function (e) {
                var target = $(this).find('input[type=radio]');
                var which = parseInt(target.val());
                if (which == 2) $('#form-field-select-4').addClass('tag-input-style');
                else $('#form-field-select-4').removeClass('tag-input-style');
            });
        }
            $("#function-table").DataTable({

                "processing": true, // for show progress bar
                "serverSide": true, // for process server side
                "filter": true, // this is for disable filter (search box)
                "orderMulti": false, // for disable multiple column at once
                "ajax": {
                    "url": "Function/LoadData",
                    "type": "POST",
                    "datatype": "json"
                },

                "columns": [
                    { "data": "Id", "name": "Id", "autoWidth": true },
                    { "data": "Name", "name": "Name", "autoWidth": true },
                    { "data": "Url", "name": "Url", "autoWidth": true },
                    { "data": "ParentId", "name": "ParentId", "autoWidth": true },
                    { "data": "SortOrder", "name": "SortOrder", "autoWidth": true },
                    { "data": "CssClass", "name": "CssClass", "autoWidth": true },
                    {
                        data: null, render: function (data, type, row) {
                            return "<div class='btn-group'><a class='btn btn-xs btn-info' href='/Function/Edit/" + row.Id + "'><i class='ace-icon fa fa-pencil-square-o bigger-120'></i></a><a href='#' class='btn btn-xs btn-danger' onclick=DeleteData('" + row.Id + "'); ><i class='ace-icon fa fa-trash-o bigger-120'></i></a></div>";
                        }
                    },
                ]


            });
        });


    function DeleteData(Id)
        {
            bootbox.confirm({
						message: "Bạn có chắc muốn xóa dòng này ...?",
						buttons: {
						  confirm: {
							 label: "Xác nhận",
							 className: "btn-primary btn-sm",
						  },
						  cancel: {
							 label: "Hủy",
							 className: "btn-sm",
						  }
						},
						callback: function(result) {
                            if (result) { Delete(Id); }
                            else { }
						}
					  }
					);
        }


        function Delete(Id)
    {
        var url = '@Url.Content("~/")' + "Function/Delete";

            $.post(url, { ID: Id }, function (data)
                {
                    if (data)
                    {
                        oTable = $('#function-table').DataTable();
                        oTable.draw();
                    }
                    else
                    {
                        alert("Có lỗi xảy ra!");
                    }
                });
    }

    </script>
}